name: PR_unit_tests

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Test and build
        run: |
          ./gradlew clean
          ./gradlew assembleRelease
      - name: Upload
          run: ./gradlew publish
