name: PullRequestFlow

on:
  pull_request: 
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkPR:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Release build
        run: ./gradlew assemble

      - name: Tests
        run: ./gradlew test
