name: PR_actions

on:
  pull_request: 
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit tests
        run: |
          ./gradlew assemble
          ./gradlew test
